# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\alber\Documents\workspace\prosthetic_interface\app\components\signal\signal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_signalW(object):
    def setupUi(self, signalW):
        signalW.setObjectName("signalW")
        signalW.resize(522, 469)
        self.verticalLayout = QtWidgets.QVBoxLayout(signalW)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(signalW)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.signalGraph = QtWidgets.QLabel(self.groupBox)
        self.signalGraph.setText("")
        self.signalGraph.setScaledContents(True)
        self.signalGraph.setAlignment(QtCore.Qt.AlignCenter)
        self.signalGraph.setObjectName("signalGraph")
        self.verticalLayout_2.addWidget(self.signalGraph)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(signalW)
        QtCore.QMetaObject.connectSlotsByName(signalW)

    def retranslateUi(self, signalW):
        _translate = QtCore.QCoreApplication.translate
        signalW.setWindowTitle(_translate("signalW", "Form"))
        self.groupBox.setTitle(_translate("signalW", "Señal"))
