# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\alber\Documents\workspace\prosthetic_interface\app\components\serialConn\serialConn.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_serialConnW(object):
    def setupUi(self, serialConnW):
        serialConnW.setObjectName("serialConnW")
        serialConnW.resize(325, 169)
        self.verticalLayout = QtWidgets.QVBoxLayout(serialConnW)
        self.verticalLayout.setObjectName("verticalLayout")
        self.serialConnBox = QtWidgets.QGroupBox(serialConnW)
        self.serialConnBox.setObjectName("serialConnBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.serialConnBox)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.serialConnBox)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.port_button = QtWidgets.QPushButton(self.frame)
        self.port_button.setObjectName("port_button")
        self.gridLayout.addWidget(self.port_button, 0, 2, 1, 1)
        self.disconect_button = QtWidgets.QPushButton(self.frame)
        self.disconect_button.setObjectName("disconect_button")
        self.gridLayout.addWidget(self.disconect_button, 2, 2, 1, 1)
        self.status_label = QtWidgets.QLabel(self.frame)
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 2, 0, 1, 1)
        self.rate_label = QtWidgets.QLabel(self.frame)
        self.rate_label.setObjectName("rate_label")
        self.gridLayout.addWidget(self.rate_label, 1, 0, 1, 1)
        self.rate_list = QtWidgets.QComboBox(self.frame)
        self.rate_list.setObjectName("rate_list")
        self.gridLayout.addWidget(self.rate_list, 1, 1, 1, 1)
        self.port_list = QtWidgets.QComboBox(self.frame)
        self.port_list.setObjectName("port_list")
        self.gridLayout.addWidget(self.port_list, 0, 1, 1, 1)
        self.marker_label = QtWidgets.QLabel(self.frame)
        self.marker_label.setObjectName("marker_label")
        self.gridLayout.addWidget(self.marker_label, 2, 1, 1, 1)
        self.port_label = QtWidgets.QLabel(self.frame)
        self.port_label.setObjectName("port_label")
        self.gridLayout.addWidget(self.port_label, 0, 0, 1, 1)
        self.update_button = QtWidgets.QPushButton(self.frame)
        self.update_button.setObjectName("update_button")
        self.gridLayout.addWidget(self.update_button, 1, 2, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 3)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.frame, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.serialConnBox)

        self.retranslateUi(serialConnW)
        QtCore.QMetaObject.connectSlotsByName(serialConnW)

    def retranslateUi(self, serialConnW):
        _translate = QtCore.QCoreApplication.translate
        serialConnW.setWindowTitle(_translate("serialConnW", "Form"))
        self.serialConnBox.setTitle(_translate("serialConnW", "Conexión serial"))
        self.port_button.setText(_translate("serialConnW", "CONECTAR"))
        self.disconect_button.setText(_translate("serialConnW", "DESCONECTAR"))
        self.status_label.setText(_translate("serialConnW", "Estado:"))
        self.rate_label.setText(_translate("serialConnW", "Tasa de transferencia"))
        self.marker_label.setText(_translate("serialConnW", "DESCONECTADO"))
        self.port_label.setText(_translate("serialConnW", "Puerto"))
        self.update_button.setText(_translate("serialConnW", "ACTUALIZAR"))
